# Python

In [1]:
type(False)

bool

In [19]:
my_str="ImranRoshan"
my_str.isalnum()
name =12

In [25]:
my_str.isalpha() or name.isint()

True

# List

In [26]:
type([])

list

In [27]:
ex =[]
type(ex)

list

In [30]:
lst = ['apple','bannana',12,13]
type(lst)

list

In [31]:
len(lst)

4

In [33]:
lst.append("Krish")
lst

['apple', 'bannana', 12, 13, 'Krish', 'Krish']

In [37]:
lst[1:4]

['bannana', 12, 13]

#### 

In [38]:
lst.append(["heelo","world"])
lst

['apple', 'bannana', 12, 13, 'Krish', 'Krish', ['heelo', 'world']]

In [42]:
lst.insert(4,"Naik")
lst

['apple', 'bannana', 12, 13, 'Naik', 'Krish', 'Krish', ['heelo', 'world']]

In [45]:
lst =[1,2,3,4,5,6]

In [46]:
sum(lst)


21

In [47]:
lst.pop()
lst

[1, 2, 3, 4, 5]

# Count():calculates total occurence of given element of list

In [49]:
lst =[1,1,2,3,4,5]
lst.count(1)

2

In [50]:
len(lst)

6

In [51]:
lst*2

[1, 1, 2, 3, 4, 5, 1, 1, 2, 3, 4, 5]

In [55]:
lst=[1,2,3,4,5]
lst.index(1)

0

# Sets

In [56]:
set_var = set()
set_var

set()

In [57]:
set_vars={1,2,3,4}
set_vars
type(set_vars)

set

In [60]:
# indexing not in sets
set_var={'s','b','c'}
set_var


{'b', 'c', 's'}

In [61]:
my_dic={"car1":"audi","car2":"bmw"}
my_dic

{'car1': 'audi', 'car2': 'bmw'}

In [62]:
type(my_dic)

dict

In [63]:
my_dic["car1"]

'audi'

In [64]:
for x in my_dic:
    print(x)

car1
car2


In [67]:
for x in my_dic.values():
    print(x)

audi
bmw


In [70]:
for x in my_dic.items():
    print(x)

('car1', 'audi')
('car2', 'bmw')


In [72]:
my_dic["car4"]="meran"
my_dic

{'car1': 'audi', 'car2': 'bmw', 'car4': 'meran'}

# Nested Dictonary

In [74]:
car1_model={"Mercedes":1960}
car2_model={"Audi":1970}
car3_model={"Ambassador":1980}
car_type={'car1':car1_model,'car2':car2_model,'car3':car3_model}
car_type

{'car1': {'Mercedes': 1960},
 'car2': {'Audi': 1970},
 'car3': {'Ambassador': 1980}}

# Tuples

In [75]:
my_tuple=tuple()

In [77]:
type(my_tuple)

tuple

# Numpy

In [78]:
import numpy as np
my_lst =[1,2,3,4,5]
arr = np.array(my_lst)

In [79]:
arr

array([1, 2, 3, 4, 5])

In [82]:
arr.shape

(5,)

In [84]:
arr1 = [1,2,3,4,5]
arr2=[2,3,4,5,6]
arr3=[5,6,7,8,9]
arr = np.array([arr1,arr2,arr3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [85]:
arr.shape

(3, 5)

In [2]:
import numpy as np
arr1 = [1,2,3,4,5]
arr2=[2,3,4,5,6]
arr3=[5,6,7,8,9]
arr = np.array([arr1,arr2,arr3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [3]:
arr.shape

(3, 5)

In [4]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 5, 6],
       [7, 8, 9]])

# indexing

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
arr[3]

4

In [8]:
arr1 = [1,2,3,4,5]
arr2=[2,3,4,5,6]
arr3=[5,6,7,8,9]
arr = np.array([arr1,arr2,arr3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [9]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9]])

In [10]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [11]:
arr[:,0:2]

array([[1, 2],
       [2, 3],
       [5, 6]])

In [12]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [14]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [17]:
arr = np.arange(0,10,step=2)

In [18]:
arr

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [21]:
# copy function and broadcoasting
arr[3:]=100
arr

array([  0,   2,   4, 100, 100])

In [26]:
lst =([1,2,3,4,5,6])
type(lst)

list

In [27]:
arr = np.array(lst)
type(arr)

numpy.ndarray

In [28]:
arr[3:]=300
arr

array([  1,   2,   3, 300, 300, 300])

In [29]:
arr1=np.copy(arr)

In [30]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 300 300 300]
[   1    2    3 1000 1000 1000]
